import type { Metadata } from "next";
import Head from "next/head"
import "./globals.css";
import { SocketProvider } from "./context/socketContext";

export const metadata: Metadata = {
  title: "Clickky",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
  <html lang="en">
       <Head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
      </Head>
      <body>
        <SocketProvider>{children}</SocketProvider>
      </body>
    </html>
  );
}
