import type { Metadata } from "next";
import "./globals.css";
import { SocketProvider } from "./context/socketContext";

export const metadata: Metadata = {
  title: "Clickky",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/icons/32.png" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body>
        <SocketProvider>{children}</SocketProvider>
      </body>
    </html>
  );
}
